strand = "CGGCAGCTGGGGGTCGTAGGGAGTTGTACTTTGACATCCCATGGAGATCAGAATATCCGGAGTCTCCACCCGATTAAGTAAACGGATTCGGAATTATGCCCGGGCACTCTGGCAGAGACGTAAGTATAAGTTGTTGGAACACACTGTTTTGTTGCGGTGTCACGCGTCATTGCCGTGTGTTAGCGTGCCTAACGGCTTTTAGCCCTAGGGTATCAAACATTAACCCACTCGTATCGGTGCCTGAACGGGGTCATTGCAGGTACAAGATGAATCTAGGCCCTTGTGGTTCTCAGTGGGTTTCATACTTTGAACTGATTGACACCCCCCGTGAAGTGGATTATCCATTCCTATAGGCGGGTCTCGCGGAAAGACCGGCAATTATATTTTAGAACAAGTACGAAGTATGTGCACTTGTATGTCTTTCAGGCAAGTTTGGGCTAGGATTACCCGATGCCTTGCCACCCTCATATCTTTCTGGTTTGCGCGCATTTGAGTTTGATTCTTCTGTAGTGGCTACACGTTTAGATCATGATGCGATTGGTTTTGCAGTACAATGTATCTGGTGGGGTGCAAGCGGCTAGCCGAAACCTGCTCGGTCCAAGATCGGACCCGCCAAACTCAGTTTCTGAACAGCCGAATTCCTATGTTCTGAGTAAGAACTCTTCTGATGCAATATGATAAATTAGAAACTTACATCGACGGGGTCTTGCACGCCTCCTGGTTTCCATAGATATACAGGCCTTGCAGAGGCACTGACTGTAATAGGTTGGAGCTCCGTACTCCTTCAATCTTTTCGCCTCTGTTATCTAATCCTTGCAGGCGCGTCTGTTATTCTAGTGGATGCACCTC"
a = 0
c = 0
g = 0
t = 0

for char in strand:
	if char == "A":
		a += 1
	if char == "C":
		c += 1
	if char == "G":
		g += 1
	if char == "T":
		t += 1
		
print(a,c,g,t)